"""WebSocket protocol handler for HTTP/1.1 Upgrade.

This module provides WebSocket handling for HTTP/1.1 connections that upgrade
from HTTP to WebSocket via the Upgrade mechanism (RFC 6455).

Unlike the HTTP/2/3 implementation, this handler must first complete the
HTTP/1.1 Upgrade handshake (101 Switching Protocols) before WebSocket
frames can be exchanged.
"""

import asyncio
import base64
import hashlib
import re
from typing import Callable

from asgiref.typing import (
    ASGI3Application,
    WebSocketAcceptEvent,
    WebSocketCloseEvent,
    WebSocketDisconnectEvent,
    WebSocketReceiveEvent,
    WebSocketScope,
    WebSocketSendEvent,
)
from loguru import logger

from .websocket_frames import (
    CloseCode,
    Opcode,
    WebSocketFrame,
    WebSocketParser,
    encode_binary_frame,
    encode_close_frame,
    encode_pong_frame,
    encode_text_frame,
    parse_close_frame,
)

# WebSocket GUID for key validation (RFC 6455)
WEBSOCKET_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"


def generate_accept_key(key: str) -> str:
    """Generate the Sec-WebSocket-Accept response key.

    Per RFC 6455, the accept key is generated by:
    1. Concatenating the client's key with the GUID
    2. Taking the SHA-1 hash
    3. Base64 encoding the result

    Args:
        key: The Sec-WebSocket-Key from the client request.

    Returns:
        The Sec-WebSocket-Accept response value.
    """
    concatenated = key + WEBSOCKET_GUID
    sha1_hash = hashlib.sha1(concatenated.encode("latin1")).digest()
    return base64.b64encode(sha1_hash).decode("ascii")


def parse_http_request(data: bytes) -> dict[str, str | dict[str, str]] | None:
    """Parse an HTTP/1.1 request.

    Args:
        data: Raw HTTP request bytes.

    Returns:
        Dictionary with parsed request fields, or None if incomplete.
    """
    try:
        # Find the end of headers
        header_end = data.find(b"\r\n\r\n")
        if header_end == -1:
            return None  # Incomplete request

        header_data = data[:header_end].decode("latin1")
        lines = header_data.split("\r\n")

        if not lines:
            return None

        # Parse request line
        request_line = lines[0]
        match = re.match(r"^(\w+)\s+(\S+)\s+HTTP/(\d\.\d)$", request_line)
        if not match:
            return None

        method, path, version = match.groups()

        # Parse headers
        headers: dict[str, str] = {}
        for line in lines[1:]:
            if ":" in line:
                name, value = line.split(":", 1)
                headers[name.strip().lower()] = value.strip()

        return {
            "method": method,
            "path": path,
            "version": version,
            "headers": headers,
            "raw_headers": header_data,
        }

    except Exception:
        return None


class WebSocketHTTP11Handler:
    """Handles WebSocket connections over HTTP/1.1 Upgrade.

    This handler manages the full HTTP/1.1 WebSocket lifecycle:
    1. Parse the HTTP Upgrade request
    2. Send 101 Switching Protocols response
    3. Handle WebSocket frames using our frame parser
    """

    def __init__(
        self,
        scope: WebSocketScope,
        app: ASGI3Application,
        send_data: Callable[[bytes], None],
        close_connection: Callable[[], None],
        websocket_key: str,
    ):
        """Initialize the WebSocket handler.

        Args:
            scope: The ASGI WebSocket scope dictionary.
            app: The ASGI application to handle the WebSocket connection.
            send_data: Callback to send raw bytes to the client.
            close_connection: Callback to close the underlying connection.
            websocket_key: The Sec-WebSocket-Key from the client request.
        """
        self.scope = scope
        self.app = app
        self._send_data = send_data
        self._close_connection = close_connection
        self.websocket_key = websocket_key

        # Frame parser for incoming data
        self._parser = WebSocketParser()

        # Queues for ASGI communication
        self._receive_queue: asyncio.Queue[
            WebSocketReceiveEvent | WebSocketDisconnectEvent
        ] = asyncio.Queue()
        self._send_queue: asyncio.Queue[
            WebSocketAcceptEvent | WebSocketSendEvent | WebSocketCloseEvent
        ] = asyncio.Queue()

        # State tracking
        self._handshake_complete = False
        self._accepted = False
        self._closed = False
        self._close_code: int | None = None
        self._close_reason: str = ""

        # Task tracking
        self._app_task: asyncio.Task | None = None
        self._sender_task: asyncio.Task | None = None

        # Message reassembly for fragmented messages
        self._message_buffer: list[bytes] = []
        self._message_type: Opcode | None = None

    async def handle(self) -> None:
        """Start handling the WebSocket connection.

        This method:
        1. Sends the websocket.connect event to the application
        2. Starts the application task
        3. Starts the sender task
        4. Waits for both tasks to complete
        """
        logger.debug("WebSocket HTTP/1.1 handler starting")

        # Send initial connect event
        connect_event: WebSocketReceiveEvent = {"type": "websocket.connect", "text": None, "bytes": None}
        await self._receive_queue.put(connect_event)

        # Start application task
        self._app_task = asyncio.create_task(self._run_app())

        # Start sender task
        self._sender_task = asyncio.create_task(self._sender())

        # Wait for both to complete
        try:
            await asyncio.gather(self._app_task, self._sender_task)
        except Exception as e:
            logger.exception(f"Error in WebSocket handler: {e}")
        finally:
            await self._cleanup()

    async def _run_app(self) -> None:
        """Run the ASGI application with WebSocket scope."""
        logger.debug("Running ASGI app")
        try:
            await self.app(self.scope, self._receive, self._send)
            logger.debug("ASGI app completed normally")
        except Exception as e:
            # Check if it's a normal WebSocket disconnect
            if "WebSocketDisconnect" in type(e).__name__:
                logger.debug(f"WebSocket disconnected: {e}")
            else:
                logger.exception(f"Error in WebSocket application: {e}")
                if not self._closed:
                    await self._close(CloseCode.INTERNAL_ERROR, "Internal server error")

    async def _receive(self) -> WebSocketReceiveEvent | WebSocketDisconnectEvent:
        """ASGI receive callable."""
        return await self._receive_queue.get()

    async def _send(self, message: WebSocketAcceptEvent | WebSocketSendEvent | WebSocketCloseEvent) -> None:
        """ASGI send callable."""
        await self._send_queue.put(message)

    async def _sender(self) -> None:
        """Process outgoing messages from the application."""
        while not self._closed:
            try:
                # Wait for message from application with timeout
                try:
                    message = await asyncio.wait_for(
                        self._send_queue.get(), timeout=0.1
                    )
                except asyncio.TimeoutError:
                    continue

                if message["type"] == "websocket.accept":
                    await self._handle_accept(message)
                elif message["type"] == "websocket.send":
                    await self._handle_send(message)
                elif message["type"] == "websocket.close":
                    await self._handle_close(message)
                    break

            except Exception as e:
                logger.exception(f"Error in WebSocket sender: {e}")
                break

    async def _handle_accept(self, message: WebSocketAcceptEvent) -> None:
        """Handle websocket.accept message from application.

        Sends the 101 Switching Protocols response to complete the handshake.
        """
        if self._accepted:
            raise RuntimeError("WebSocket already accepted")

        self._accepted = True

        # Generate accept key
        accept_key = generate_accept_key(self.websocket_key)

        # Build response headers
        headers = [
            b"HTTP/1.1 101 Switching Protocols",
            b"Upgrade: websocket",
            b"Connection: Upgrade",
            f"Sec-WebSocket-Accept: {accept_key}".encode(),
        ]

        # Add subprotocol if selected
        subprotocol = message.get("subprotocol")
        if subprotocol:
            headers.append(f"Sec-WebSocket-Protocol: {subprotocol}".encode())

        # Add any additional headers from the application
        for name, value in message.get("headers", []):
            headers.append(f"{name.decode()}: {value.decode()}".encode())

        # Send the response
        response = b"\r\n".join(headers) + b"\r\n\r\n"
        self._send_data(response)
        self._handshake_complete = True

        logger.debug(
            f"WebSocket handshake complete (subprotocol: {subprotocol})"
        )

    async def _handle_send(self, message: WebSocketSendEvent) -> None:
        """Handle websocket.send message from application."""
        if not self._accepted:
            raise RuntimeError("WebSocket not accepted yet")

        if self._closed:
            logger.warning("Attempted to send on closed WebSocket")
            return

        try:
            if "bytes" in message and message["bytes"] is not None:
                # Send binary message
                frame_data = encode_binary_frame(message["bytes"])
                self._send_data(frame_data)
            elif "text" in message and message["text"] is not None:
                # Send text message
                frame_data = encode_text_frame(message["text"])
                self._send_data(frame_data)
            else:
                raise ValueError(
                    "WebSocket send message must have 'bytes' or 'text'"
                )
        except Exception as e:
            logger.error(f"Error sending WebSocket frame: {e}")
            raise

    async def _handle_close(self, message: WebSocketCloseEvent) -> None:
        """Handle websocket.close message from application."""
        code = message.get("code", CloseCode.NORMAL)
        reason = message.get("reason") or ""
        await self._close(code, reason)

    def data_received(self, data: bytes) -> None:
        """Handle incoming WebSocket data.

        Args:
            data: Raw bytes received from the network.
        """
        if self._closed:
            return

        try:
            frames = self._parser.receive_data(data)
            for frame in frames:
                asyncio.create_task(self._handle_frame(frame))
        except Exception as e:
            logger.error(f"WebSocket protocol error: {e}")
            asyncio.create_task(
                self._close(CloseCode.PROTOCOL_ERROR, str(e))
            )

    async def _handle_frame(self, frame: WebSocketFrame) -> None:
        """Handle a parsed WebSocket frame."""
        if self._closed:
            return

        try:
            if frame.opcode == Opcode.TEXT:
                if frame.fin:
                    # Complete text message
                    await self._receive_queue.put({
                        "type": "websocket.receive",
                        "text": frame.payload.decode("utf-8", errors="replace"),
                        "bytes": None,
                    })
                else:
                    # Start of fragmented text message
                    self._message_type = Opcode.TEXT
                    self._message_buffer = [frame.payload]

            elif frame.opcode == Opcode.BINARY:
                if frame.fin:
                    # Complete binary message
                    await self._receive_queue.put({
                        "type": "websocket.receive",
                        "bytes": frame.payload,
                        "text": None,
                    })
                else:
                    # Start of fragmented binary message
                    self._message_type = Opcode.BINARY
                    self._message_buffer = [frame.payload]

            elif frame.opcode == Opcode.CONTINUATION:
                # Continuation frame
                if self._message_type is None:
                    raise Exception("Unexpected continuation frame")

                self._message_buffer.append(frame.payload)

                if frame.fin:
                    # End of fragmented message
                    complete_payload = b"".join(self._message_buffer)

                    if self._message_type == Opcode.TEXT:
                        await self._receive_queue.put({
                            "type": "websocket.receive",
                            "text": complete_payload.decode("utf-8", errors="replace"),
                            "bytes": None,
                        })
                    else:  # BINARY
                        await self._receive_queue.put({
                            "type": "websocket.receive",
                            "bytes": complete_payload,
                            "text": None,
                        })

                    self._message_type = None
                    self._message_buffer = []

            elif frame.opcode == Opcode.CLOSE:
                # Client initiated close
                code, reason = parse_close_frame(frame.payload)
                logger.debug(f"WebSocket close from client: {code} {reason}")

                # Send disconnect event to application
                await self._receive_queue.put({
                    "type": "websocket.disconnect",
                    "code": code,
                    "reason": reason,
                })

                # Echo the close frame
                if not self._closed:
                    await self._close(code, reason, echo=True)

            elif frame.opcode == Opcode.PING:
                # Respond to ping with pong
                pong_frame = encode_pong_frame(frame.payload)
                self._send_data(pong_frame)

            elif frame.opcode == Opcode.PONG:
                # Pong received
                logger.debug("Received pong frame")

        except Exception as e:
            logger.exception(f"Error handling WebSocket frame: {e}")

    async def _close(
        self,
        code: int = CloseCode.NORMAL,
        reason: str = "",
        echo: bool = False,
    ) -> None:
        """Close the WebSocket connection.

        Args:
            code: The WebSocket close code.
            reason: The close reason string.
            echo: If True, this is an echo close (don't send disconnect event).
        """
        if self._closed:
            return

        self._closed = True
        self._close_code = code
        self._close_reason = reason

        try:
            # Send close frame
            close_frame = encode_close_frame(code, reason)
            self._send_data(close_frame)
        except Exception as e:
            logger.debug(f"Error sending close frame: {e}")

        # Close underlying connection
        try:
            self._close_connection()
        except Exception as e:
            logger.debug(f"Error closing connection: {e}")

        # Send disconnect event to application if not already sent
        if not echo:
            await self._receive_queue.put({
                "type": "websocket.disconnect",
                "code": code,
                "reason": reason,
            })

        logger.debug(f"WebSocket closed: {code} {reason}")

    async def _cleanup(self) -> None:
        """Clean up resources."""
        # Cancel tasks if they're still running
        if self._app_task and not self._app_task.done():
            self._app_task.cancel()
            try:
                await self._app_task
            except asyncio.CancelledError:
                pass

        if self._sender_task and not self._sender_task.done():
            self._sender_task.cancel()
            try:
                await self._sender_task
            except asyncio.CancelledError:
                pass

        # Ensure connection is closed
        if not self._closed:
            await self._close(CloseCode.ABNORMAL_CLOSURE, "Connection lost")

    @property
    def closed(self) -> bool:
        """Check if the connection is closed."""
        return self._closed
